//! AuditTrail DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::AuditTrail;
use crate::domain::entity::AuditEventType;
use crate::domain::entity::AuditStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new AuditTrail
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateAuditTrailDto {
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
    #[serde(alias = "event_type")]
    pub event_type: AuditEventType,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub action: String,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub actor: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub changed: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub status: AuditStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "correlation_id")]
    pub correlation_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "client_ip")]
    pub client_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_agent")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "http_method")]
    pub http_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resource_path")]
    pub resource_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub txid: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a AuditTrail
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateAuditTrailDto {
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "occurred_at")]
    pub occurred_at: DateTime<Utc>,
    #[serde(alias = "event_type")]
    pub event_type: AuditEventType,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub action: String,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub actor: String,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub changed: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    pub status: AuditStatus,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "correlation_id")]
    pub correlation_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "client_ip")]
    pub client_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "user_agent")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "http_method")]
    pub http_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "resource_path")]
    pub resource_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub txid: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a AuditTrail
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchAuditTrailDto {
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "occurred_at")]
    pub occurred_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_type")]
    pub event_type: Option<AuditEventType>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub actor: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 120)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_type")]
    pub subject_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 160)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "subject_id")]
    pub subject_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub changed: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<AuditStatus>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "correlation_id")]
    pub correlation_id: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 64)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "client_ip")]
    pub client_ip: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "user_agent")]
    pub user_agent: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 10)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "http_method")]
    pub http_method: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 512)))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "resource_path")]
    pub resource_path: Option<String>,
    #[cfg_attr(feature = "validation", validate(length(max = 32)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub txid: Option<String>,
}

impl PatchAuditTrailDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.occurred_at.is_some() || self.event_type.is_some() || self.action.is_some() || self.actor.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.changed.is_some() || self.reason.is_some() || self.status.is_some() || self.correlation_id.is_some() || self.client_ip.is_some() || self.user_agent.is_some() || self.http_method.is_some() || self.resource_path.is_some() || self.txid.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for AuditTrail entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AuditTrailResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub occurred_at: DateTime<Utc>,
    pub event_type: AuditEventType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub action: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub actor: String,
    pub subject_type: Option<String>,
    pub subject_id: Option<String>,
    pub changed: Option<serde_json::Value>,
    pub reason: Option<String>,
    pub status: AuditStatus,
    pub correlation_id: Option<String>,
    pub client_ip: Option<String>,
    pub user_agent: Option<String>,
    pub http_method: Option<String>,
    pub resource_path: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub txid: String,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for AuditTrail entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AuditTrailListResponseDto {
    /// List of items
    pub items: Vec<AuditTrailResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl AuditTrailListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<AuditTrailResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct AuditTrailSummaryDto {
    pub id: Uuid,
    pub occurred_at: DateTime<Utc>,
    pub event_type: AuditEventType,
    pub action: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<AuditTrail> for AuditTrailResponseDto {
    fn from(entity: AuditTrail) -> Self {
        Self {
            id: entity.id,
            occurred_at: entity.occurred_at,
            event_type: entity.event_type,
            action: entity.action,
            actor: entity.actor,
            subject_type: entity.subject_type,
            subject_id: entity.subject_id,
            changed: entity.changed,
            reason: entity.reason,
            status: entity.status,
            correlation_id: entity.correlation_id,
            client_ip: entity.client_ip,
            user_agent: entity.user_agent,
            http_method: entity.http_method,
            resource_path: entity.resource_path,
            txid: entity.txid,
        }
    }
}

impl From<AuditTrail> for AuditTrailSummaryDto {
    fn from(entity: AuditTrail) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            occurred_at: entity.occurred_at,
            event_type: entity.event_type,
            action: entity.action,
            created_at,
        }
    }
}

impl From<CreateAuditTrailDto> for AuditTrail {
    fn from(dto: CreateAuditTrailDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            occurred_at: dto.occurred_at,
            event_type: dto.event_type,
            action: dto.action,
            actor: dto.actor,
            subject_type: dto.subject_type,
            subject_id: dto.subject_id,
            changed: dto.changed,
            reason: dto.reason,
            status: dto.status,
            correlation_id: dto.correlation_id,
            client_ip: dto.client_ip,
            user_agent: dto.user_agent,
            http_method: dto.http_method,
            resource_path: dto.resource_path,
            txid: dto.txid,
        }
    }
}

impl From<&AuditTrail> for AuditTrailResponseDto {
    fn from(entity: &AuditTrail) -> Self {
        Self {
            id: entity.id.clone(),
            occurred_at: entity.occurred_at.clone(),
            event_type: entity.event_type.clone(),
            action: entity.action.clone(),
            actor: entity.actor.clone(),
            subject_type: entity.subject_type.clone(),
            subject_id: entity.subject_id.clone(),
            changed: entity.changed.clone(),
            reason: entity.reason.clone(),
            status: entity.status.clone(),
            correlation_id: entity.correlation_id.clone(),
            client_ip: entity.client_ip.clone(),
            user_agent: entity.user_agent.clone(),
            http_method: entity.http_method.clone(),
            resource_path: entity.resource_path.clone(),
            txid: entity.txid.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateAuditTrailDto> for AuditTrail {
    fn from_create_dto(dto: CreateAuditTrailDto) -> backbone_core::ServiceResult<Self> {
        Ok(AuditTrail::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateAuditTrailDto> for AuditTrail {
    fn apply_update(mut self, dto: UpdateAuditTrailDto) -> backbone_core::ServiceResult<Self> {
        self.occurred_at = dto.occurred_at;
        self.event_type = dto.event_type;
        self.action = dto.action;
        self.actor = dto.actor;
        self.subject_type = dto.subject_type;
        self.subject_id = dto.subject_id;
        self.changed = dto.changed;
        self.reason = dto.reason;
        self.status = dto.status;
        self.correlation_id = dto.correlation_id;
        self.client_ip = dto.client_ip;
        self.user_agent = dto.user_agent;
        self.http_method = dto.http_method;
        self.resource_path = dto.resource_path;
        self.txid = dto.txid;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to AuditTrail here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
