//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod audit_trail_domain_policy;

pub use audit_trail_domain_policy::AuditTrailDomainPolicy;

// <<< CUSTOM
// END CUSTOM
