//! Application service for AuditTrail entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `audit_trail_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateAuditTrailDto, UpdateAuditTrailDto};
use crate::domain::entity::AuditTrail;
use crate::infrastructure::persistence::AuditTrailRepository;

/// Application service for AuditTrail entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `audit_trail_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct AuditTrailServiceCustom {
///     inner: Arc<AuditTrailService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type AuditTrailService = GenericCrudService<
    AuditTrail,
    CreateAuditTrailDto,
    UpdateAuditTrailDto,
    AuditTrailRepository,
>;

// <<< CUSTOM
// END CUSTOM
