//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod audit_trail_service;

// <<< CUSTOM
// The same-transaction audit verbs (ADR-0025 service-emitted lane).
pub mod audit_trail_service_custom;
pub use audit_trail_service_custom::{append, AuditEvent, AuditHistoryProvider, AuditTrailWriter};
// END CUSTOM

pub use audit_trail_service::AuditTrailService;
// <<< CUSTOM
// END CUSTOM
