-- AuditTrail Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the auditlog.audit_trails table.
-- Customize this file to add your initial data.

-- INSERT INTO auditlog.audit_trails (
--     id,
--     occurred_at,
--     event_type,
--     action,
--     actor,
--     subject_type,
--     subject_id,
--     changed,
--     reason,
--     status,
--     correlation_id,
--     client_ip,
--     user_agent,
--     http_method,
--     resource_path,
--     txid
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO auditlog.audit_trails (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

