-- Enum types for auditlog module
-- Generated by metaphor-schema

-- Create audit_event_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_event_type') THEN
        CREATE TYPE audit_event_type AS ENUM ('data_change', 'refusal', 'security_edge');
    END IF;
END
$$;

-- Create audit_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_status') THEN
        CREATE TYPE audit_status AS ENUM ('success', 'failure');
    END IF;
END
$$;

