-- Migration: Create audit_trails table
-- Generated by metaphor-schema

-- Create audit_event_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_event_type') THEN
        CREATE TYPE audit_event_type AS ENUM ('data_change', 'refusal', 'security_edge');
    END IF;
END
$$;

-- Create audit_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'audit_status') THEN
        CREATE TYPE audit_status AS ENUM ('success', 'failure');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS auditlog;

CREATE TABLE IF NOT EXISTS auditlog.audit_trails (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type audit_event_type NOT NULL,
    action TEXT NOT NULL,
    actor TEXT NOT NULL,
    subject_type TEXT,
    subject_id TEXT,
    changed JSONB,
    reason TEXT,
    status audit_status NOT NULL,
    correlation_id TEXT,
    client_ip TEXT,
    user_agent TEXT,
    http_method TEXT,
    resource_path TEXT,
    txid TEXT NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_audit_trails_subject_type_subject_id ON auditlog.audit_trails (subject_type, subject_id);

CREATE INDEX IF NOT EXISTS idx_audit_trails_event_type_occurred_at ON auditlog.audit_trails (event_type, occurred_at);

CREATE INDEX IF NOT EXISTS idx_audit_trails_actor_occurred_at ON auditlog.audit_trails (actor, occurred_at);

CREATE INDEX IF NOT EXISTS idx_audit_trails_correlation_id ON auditlog.audit_trails (correlation_id);
