//! Event handler trait for AuditTrail events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::AuditTrailEvent;

/// Event handler for AuditTrail events.
/// Implement this trait to react to AuditTrail lifecycle events.
pub trait AuditTrailEventHandler: EventHandler<AuditTrailEvent> {}
