//! Domain events for AuditTrail entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::AuditTrail;

/// Domain events for AuditTrail — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<AuditTrail>)` variant.
pub type AuditTrailEvent = CrudEvent<AuditTrail>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for AuditTrail events.
pub type AuditTrailEventPublisher = Arc<dyn CrudEventPublisher<AuditTrail> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopAuditTrailEventPublisher = NoOpCrudEventPublisher<AuditTrail>;
