//! Repository trait for AuditTrail aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the AuditTrail aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{AuditTrail, AuditEventType, AuditStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AuditTrailPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl AuditTrailPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct AuditTrailPaginatedResult {
    pub data: Vec<AuditTrail>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct AuditTrailFilter {
    pub event_type: Option<AuditEventType>,
    pub action: Option<String>,
    pub actor: Option<String>,
    pub subject_type: Option<String>,
    pub subject_id: Option<String>,
    pub reason: Option<String>,
    pub status: Option<AuditStatus>,
    pub correlation_id: Option<String>,
    pub client_ip: Option<String>,
    pub user_agent: Option<String>,
    pub http_method: Option<String>,
    pub resource_path: Option<String>,
    pub txid: Option<String>,
}

impl AuditTrailFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.event_type.is_some() || self.action.is_some() || self.actor.is_some() || self.subject_type.is_some() || self.subject_id.is_some() || self.reason.is_some() || self.status.is_some() || self.correlation_id.is_some() || self.client_ip.is_some() || self.user_agent.is_some() || self.http_method.is_some() || self.resource_path.is_some() || self.txid.is_some()
    }
}

/// Repository trait for AuditTrail aggregate
///
/// This trait defines the persistence contract for AuditTrail entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait AuditTrailRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new audit_trail entity
    async fn save(&self, entity: &AuditTrail) -> Result<AuditTrail>;

    /// Find audit_trail by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<AuditTrail>>;

    /// Find all audit_trail entities
    async fn find_all(&self) -> Result<Vec<AuditTrail>>;

    /// Update audit_trail by ID
    async fn update(&self, id: &str, entity: &AuditTrail) -> Result<Option<AuditTrail>>;

    /// Delete audit_trail by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List audit_trail with pagination
    async fn list(&self, params: AuditTrailPaginationParams) -> Result<AuditTrailPaginatedResult>;

    /// List audit_trail with pagination and filters
    async fn list_with_filters(&self, params: AuditTrailPaginationParams, filters: AuditTrailFilter) -> Result<AuditTrailPaginatedResult>;

    /// Count all audit_trail entities
    async fn count(&self) -> Result<u64>;

    /// Count audit_trail entities matching filters
    async fn count_with_filters(&self, filters: AuditTrailFilter) -> Result<u64>;

    /// Check if audit_trail exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save audit_trail entities
    async fn bulk_save(&self, entities: &[AuditTrail]) -> Result<Vec<AuditTrail>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
