//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod audit_trail_repository;

// Re-exports
pub use audit_trail_repository::{
    AuditTrailRepository,
    AuditTrailPaginationParams,
    AuditTrailPaginatedResult,
    AuditTrailFilter,
};
