//! Validator for AuditTrail entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<AuditTrail>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::AuditTrail;

/// Validator type alias for AuditTrail entities.
pub type AuditTrailValidator = EntityValidator<AuditTrail>;

/// Build a validator for AuditTrail with all schema-defined field rules.
pub fn audit_trail_validator() -> AuditTrailValidator {
    EntityValidator::new()
        .rule(RequiredString::new("action", |e: &AuditTrail| &e.action))
        .rule(RequiredString::new("actor", |e: &AuditTrail| &e.actor))
        .rule(OptionalNotBlank::new("subject_type", |e: &AuditTrail| e.subject_type.as_deref()))
        .rule(OptionalNotBlank::new("subject_id", |e: &AuditTrail| e.subject_id.as_deref()))
        .rule(OptionalNotBlank::new("reason", |e: &AuditTrail| e.reason.as_deref()))
        .rule(OptionalNotBlank::new("correlation_id", |e: &AuditTrail| e.correlation_id.as_deref()))
        .rule(OptionalNotBlank::new("client_ip", |e: &AuditTrail| e.client_ip.as_deref()))
        .rule(OptionalNotBlank::new("user_agent", |e: &AuditTrail| e.user_agent.as_deref()))
        .rule(OptionalNotBlank::new("http_method", |e: &AuditTrail| e.http_method.as_deref()))
        .rule(OptionalNotBlank::new("resource_path", |e: &AuditTrail| e.resource_path.as_deref()))
        .rule(RequiredString::new("txid", |e: &AuditTrail| &e.txid))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
