//! Auditlog Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::AuditTrailService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// AuditTrail service
    pub audit_trail_service: Arc<AuditTrailService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        audit_trail_service: Arc<AuditTrailService>
    ) -> Self {
        Self {
            audit_trail_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::AuditlogModule) -> Self {
        Self {
            audit_trail_service: module.audit_trail_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    audit_trail_service: Option<Arc<AuditTrailService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the AuditTrail service.
    pub fn with_audit_trail_service(mut self, service: Arc<AuditTrailService>) -> Self {
        self.audit_trail_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            audit_trail_service: self.audit_trail_service.expect("audit_trail_service is required"),
        }
    }
}
