//! Public events for Auditlog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// AUDITTRAIL EVENTS
// ============================================================================

/// Event published when a AuditTrail is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailCreatedEvent {
    pub id: AuditTrailId,
    pub data: AuditTrailDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AuditTrail is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailUpdatedEvent {
    pub id: AuditTrailId,
    pub data: AuditTrailDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a AuditTrail is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailDeletedEvent {
    pub id: AuditTrailId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Auditlog module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AuditlogEvent {
    AuditTrailCreated(AuditTrailCreatedEvent),
    AuditTrailUpdated(AuditTrailUpdatedEvent),
    AuditTrailDeleted(AuditTrailDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditlogEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for AuditlogEventMetadata {
    fn default() -> Self {
        Self {
            module: "auditlog",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
