//! Auditlog Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Auditlog exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use auditlog::exports::{AuditTrailDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `AuditTrailDto` - Data transfer object for AuditTrail
/// - `AuditTrailSummary` - Summary view of AuditTrail
/// - `AuditTrailId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `AuditTrailCreatedEvent` - Published when AuditTrail is created
/// - `AuditTrailUpdatedEvent` - Published when AuditTrail is updated
/// - `AuditTrailDeletedEvent` - Published when AuditTrail is deleted
pub struct ExportSummary;
