//! Public types for Auditlog module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// AUDITTRAIL TYPES
// ============================================================================

/// Type-safe ID for AuditTrail
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct AuditTrailId(pub Uuid);

impl AuditTrailId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for AuditTrailId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<AuditTrailId> for Uuid {
    fn from(id: AuditTrailId) -> Self {
        id.0
    }
}

/// Data transfer object for AuditTrail
///
/// This is the public representation of AuditTrail for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailDto {
    pub id: AuditTrailId,
    pub occurred_at: DateTime<Utc>,
    pub event_type: AuditEventType,
    pub action: String,
    pub actor: String,
    pub subject_type: Option<String>,
    pub subject_id: Option<String>,
    pub changed: Option<serde_json::Value>,
    pub reason: Option<String>,
    pub status: AuditStatus,
    pub correlation_id: Option<String>,
    pub client_ip: Option<String>,
    pub user_agent: Option<String>,
    pub http_method: Option<String>,
    pub resource_path: Option<String>,
    pub txid: String,
}

/// Summary view of AuditTrail for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailSummary {
    pub id: AuditTrailId,
    pub status: AuditStatus,
}

/// Reference to AuditTrail for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditTrailRef {
    pub id: AuditTrailId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
