//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod audit_trail_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use audit_trail_handler::{create_audit_trail_routes, create_audit_trail_read_routes, create_audit_trail_write_routes};
// <<< CUSTOM
// END CUSTOM
